### ISSUE TITLE
About CFD results can not be downloaded

### ISSUE THREAD

**Issue by pcl-china** [aaronbuhendwa/twophasePINN#1]
Hello, the link of the CFD results you uploaded is invalid, can you upload it again?

**Comment by RahulSundar** [comment]
Dear Aaron, 
I face a similar issue with regard to the CFD data. Please let us know if you could share the CFD data so that the results can be reprpoduced with your code. 
Regards,
Rahul

**Comment by aaronbuhendwa** [comment]
Just updated the link.

**Comment by aaronbuhendwa** [comment]
closing issue.
